In [ ]:
#импорт библиотеки
import numpy as np

In [ ]:
#массив из 10 нулей
array=np.zeros(10)
print("10 nuley:")
print(array)

10 nuley:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
#массив из 10 единиц
array=np.ones(10)
print("10 edinic")
print(array)

10 edinic
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [ ]:
#массив из 10 пятерок
array=np.ones(10)*5
print("10 pyaterok:")
print(array)

10 pyaterok:
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [ ]:
z=np.full(10,5)
print(z)

In [ ]:
#массив от 10 до 50
array=np.arange(10,51)
print("ot 10 do 50:")
print(array)

NameError: ignored

In [ ]:
array=np.arange(10,51,2)
print("ot 10 do 50:")
print(array)

ot 10 do 50:
[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


In [ ]:
for a in range(10, 51, 2):
  print(a)

10
12
14
16
18
20
22
24
26
28
30
32
34
36
38
40
42
44
46
48
50


In [ ]:
#матрица 3х3 с числами от 0 до 8
matric =  np.arange(0, 9).reshape(3,3)
print(matric)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
#единич. матрица
matric = np.eye(3)
print(matric)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
#от 0 до 1 случ.
rand = np.random.rand(1)
print("ot 0 do 1")
print(rand)

ot 0 do 1
[0.85743579]


In [ ]:
a=np.random.rand()
print(a)

0.5582320725014768


In [ ]:
rand = np.random.rand(25)
print("25 random numbers:")
print(rand)

25 random numbers:
[0.20561384 0.32389806 0.25420958 0.18623343 0.9898214  0.93585986
 0.47158995 0.81775157 0.78704254 0.09842721 0.72113033 0.51288986
 0.70382396 0.48652772 0.44161927 0.8798196  0.21551697 0.6555605
 0.52212858 0.7262429  0.11294877 0.24382585 0.20455466 0.1633383
 0.09618881]


In [ ]:
arr=np.random.rand(7,4)
print(arr)

[[0.98531117 0.93058163 0.29636505 0.8206408 ]
 [0.8064953  0.7453414  0.24416499 0.91468498]
 [0.62527348 0.91592379 0.93984699 0.51848745]
 [0.78767015 0.19790448 0.58346422 0.328433  ]
 [0.25142253 0.78351948 0.40429008 0.75560187]
 [0.69038154 0.95541366 0.76806028 0.75320672]
 [0.56163699 0.49543947 0.33981057 0.86872928]]


In [ ]:
mat = np.arange(0.01, 1.01, 0.01).reshape(10, 10)
print(mat)

[[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 ]
 [0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.2 ]
 [0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.3 ]
 [0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4 ]
 [0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5 ]
 [0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59 0.6 ]
 [0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7 ]
 [0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8 ]
 [0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89 0.9 ]
 [0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98 0.99 1.  ]]


In [ ]:
mat = np.arange(1,26).reshape(5,5)
print(mat)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [ ]:
print('array =', mat[2:, 1:])

array = [[12 13 14 15]
 [17 18 19 20]
 [22 23 24 25]]


In [ ]:
dv = mat[mat == 20]
print(dv)

[20]


In [ ]:
print('array =', mat[0:3, 1].reshape(3,1))

array = [[ 2]
 [ 7]
 [12]]


In [ ]:
mat=np.arange(1,26).reshape(5,5)
print(mat[0:3, 1:2])

[[ 2]
 [ 7]
 [12]]


In [ ]:
print('array =', mat[4:])

array = [[21 22 23 24 25]]


In [ ]:
print('array =', mat[3:])

array = [[16 17 18 19 20]
 [21 22 23 24 25]]


In [ ]:
print(mat.sum())

325


In [ ]:
print(mat.std())

7.211102550927978


In [ ]:
print(mat.sum(axis=0))

[55 60 65 70 75]


In [ ]:
#dop
#матрица с рандомными знач. 3х3х3
Z = np.random.random((3,3,3))
print(Z)

[[[0.39271922 0.32654824 0.52763857]
  [0.30279102 0.72621221 0.53236416]
  [0.60060995 0.88217839 0.87283896]]

 [[0.23216679 0.1176809  0.49331302]
  [0.02245216 0.20580649 0.6154609 ]
  [0.29883415 0.66426409 0.01897479]]

 [[0.17064675 0.65278214 0.83759704]
  [0.29111219 0.97225507 0.48095733]
  [0.96188183 0.64898012 0.31120555]]]


In [ ]:
#рандом. матрица + минимум и максимум
Z = np.random.random((10,10))
Zmin, Zmax = Z.min(), Z.max()
print(Z, "                     ", Zmin, Zmax)

[[0.53048178 0.03622129 0.79465928 0.07134783 0.72888314 0.27926684
  0.26055998 0.2028793  0.09187171 0.61883744]
 [0.97679601 0.89293385 0.87436053 0.28362858 0.47500904 0.79867842
  0.81520028 0.92616554 0.09481199 0.93656922]
 [0.38976678 0.32471265 0.10774983 0.91413717 0.7268195  0.30180203
  0.80121609 0.41166687 0.78925825 0.28491558]
 [0.80264067 0.18135133 0.40645522 0.63327869 0.18006798 0.85428491
  0.38070411 0.81466516 0.63166948 0.30788819]
 [0.33976833 0.51560622 0.79501165 0.48408956 0.44226199 0.45856306
  0.28556946 0.82032578 0.46346903 0.60556953]
 [0.8317668  0.33432258 0.17717061 0.57899693 0.73583673 0.5612031
  0.82067853 0.34816334 0.67785079 0.56522616]
 [0.69079814 0.96905131 0.54019062 0.67719114 0.72446178 0.90310405
  0.41425937 0.69802098 0.61062313 0.18932369]
 [0.20465165 0.76377258 0.23337882 0.12712047 0.97843926 0.49724698
  0.74888893 0.11936655 0.26498775 0.22124715]
 [0.83740873 0.3283955  0.70707915 0.37292628 0.60910051 0.54492572
  0.04519198 

In [ ]:
#выявление ненулевых элементов массива
x = np.array([1, 0, 0, 0])
print("Массив")
print(x)
print("Есть ненулевые элементы:")
print(np.any(x))
x = np.array([0, 0, 0, 0])
print("Массив")
print(x)
print("Есть ненулевые элементы:")
print(np.any(x))
x = np.array([0, 0, 1, 1])
print("Массив")
print(x)
print("Есть ненулевые элементы:")
print(np.any(x))

Массив
[1 0 0 0]
Есть ненулевые элементы:
True
Массив
[0 0 0 0]
Есть ненулевые элементы:
False
Массив
[0 0 1 1]
Есть ненулевые элементы:
True
